---
- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: ap-south-1
    ssh_private_key: /path/to/your/private_key.pem
  tasks:
    - name: Create security group
      ec2_group:
        name: my-security-group
        description: Security group for port 8080
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 instance
      ec2_instance:
        key_name: cicd
        instance_type: t2.micro
        image: ami-0c55b159cbfafe1f0
        wait: yes
        count: 1
        security_groups:
          - my-security-group
        region: "{{ region }}"
        tags:
          Name: example-instance
      register: ec2

- name: SSH into EC2 instance
  hosts: ec2
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: "{{ ssh_private_key }}"
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        timeout: 300

