name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t springboot-app .

    - name: Save Docker image to tar
      run: docker save -o springboot-app.tar springboot-app

    - name: Copy Docker image to Ubuntu server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "springboot-app.tar"
        target: "~/springboot-app.tar"
        debug: true

    - name: Echo host key and username
      run: |
        echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
        echo "EC2_USER: ${{ secrets.EC2_USER }}"

    - name: SSH into Ubuntu server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          docker load -i ~/springboot-app.tar
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d -p 8080:8080 --name springboot-app springboot-app:latest
        debug: true
