name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t springboot-app .

    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag springboot-app "${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest"

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest"

    - name: SSH into Ubuntu server and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          docker pull "${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest"
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d -p 8080:8080 --name springboot-app "${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest"
        debug: true
